# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Online tukan sanctuary'
description:      'Binary exploitation, for the most part'
url:              https://andigena.github.io
baseurl:          /

author:
  name:           'tukan'
  url:            https://twitter.com/kapteinemalje

paginate:         5

# Custom vars

github:
  repo:           https://github.com/andigena
